### PR TITLE
Remove temlate interface searchKnn

### PR DESCRIPTION
**Pull request by uestc-lfs**
In issue #146, i add a templae interface 
https://github.com/nmslib/hnswlib/blob/3c6a84fb54a2a92dc4b7dc3e13dbae3d99892444/hnswlib/hnswlib.h#L74-L76
But it cannot be overrided. So I removed the template and make it a virtual function.

### CODE REVIEW

**Comment by uestc-lfs** [comment]
Why is this pr not merged?

**Comment by yurymalkov** [comment]
Thanks for the PR! And sorry for an extremely late response.
One thing it seems it breaks the bruteforce C++ code (we do not have tests for it). This can be easily fixed by moving the function to the interface (as it does not depend on the algorithm).
Secondly, I think having two methods with the same name, but different semantics is not a good move. I think renaming the function to explicitly represent the difference `knnSearchFillCloserFirst` might help with that.

**Comment by uestc-lfs** [comment]
Thank you for your reply. So we should only keep the following interface
https://github.com/nmslib/hnswlib/blob/2571bdb6ef3f91d6f4c2e59178fde49055d2f980/hnswlib/hnswlib.h#L73

And add interfaces like `knnSearchFillCloserFirst`.
Am I right?

**Comment by yurymalkov** [comment]
Yes. That would work!
 It would be nice if the interface would have the same semantics (input, output types)

**Comment by uestc-lfs** [comment]
image
@yurymalkov which interface do you prefer. One returns a `vector` while another returns a `priority_queue`.

**Comment by yurymalkov** [comment]
Hi @uestc-lfs , after some thinking I agree the vector option should be actually better as it is more flexible and can be used both ways by the user.
Probably even a single order option would be enough for practical applications (CloserFirst). Please let me know what you think.

**Comment by uestc-lfs** [comment]
> Hi @uestc-lfs , after some thinking I agree the vector option should be actually better as it is more flexible and can be used both ways by the user.
> Probably even a single order option would be enough for practical applications (CloserFirst). Please let me know what you think.

I agree

**Comment by uestc-lfs** [comment]
@yurymalkov I have finished my code. How do you like it?

**Comment by yurymalkov** [comment]
Great! Thank you so much! And apologies that it took so long!

**Pull request merged**
