### PR TITLE
add tag search

### PR DESCRIPTION
**Pull request by caohassl**
I notice the issue（Support "skipping" nodes during traversal? #294） and support it , further supports tag search～

1、when building the index , enable to define the tag of the vector 
2、when the build is finished，add a inverted file to store those tags 
3、when querying,  use the inverted file to skip nodes by tag (or id)
4、add a python file to test

### CODE REVIEW

**Comment by yurymalkov** [comment]
Hi @caohassl ,

Thank you for PR! It seems it has some conflict (in terms of functionality) with #402, so we would need to figure out how to merge them. 
It also seems that windows tests are failing due to `dirent.h`

**Comment by caohassl** [comment]
Hi @yurymalkov 

Thanks for the reply！
I have read the PR #402，it seems that the ID positive filtering(keeping the nodes we need) has already been supported .

The first scenario is that we need to discard some unnecessary nodes，not only just keep the nodes we need in the scan. 
The second scenario is that we also need to find the TOPN that satisfies the particular tag, rather than taking TOPN + 1000 and filtering out 1000

To support ID filtering(positive and negative)  and tag filtering，I commit the PR (and fix the ci error)。

**Comment by dyashuni** [comment]
Hi @caohassl, why did you close the PR?

**Comment by caohassl** [comment]
hi @dyashuni 

I realized that a lot of filtering may cause performance problem, so I closed the PR.
I will try to add a threshold to jump out the scan earlier, if the performance is good, and then I will reopen it

**Comment by dyashuni** [comment]
@caohassl Thank you. Yes, heavy filtering makes search slow.
I think there is no need to create a new class `SearchHNSW` because its code is almost the same as the code of the `HierarchicalNSW` class. You can use the `HierarchicalNSW` class with a custom implementation of `FilterFunctor` to avoid code duplication. If serialization is required you can add serialization/deserialization methods to your implementation of `FilterFunctor` as well.

**Pull request closed without merging**
