### PR TITLE
Java bindings using Java Native Access

### PR DESCRIPTION
**Pull request by hussamaa**
Hi,

I hope you're well. 

We recently created some java bindings to native using java native access. It was created based on your python bindings and offers a good performance. It might help others that also want to use hnswlib in java projects.

Could we add a link to this implementation in your section: Other Implementation?

Thanks,
Hussama

### CODE REVIEW

**Comment by yurymalkov** [comment]
Hi @hussamaa,
Thank you! Sure, I can add the link.

**Comment by hussamaa** [comment]
Hi @yurymalkov, 

Thank you so much for your quick feedback and response. 

Sorry for the spam you might have received. I closed this one opened another PR with the changes to develop. 

Once again, thank you so much and have a great evening! 

Best, 
Hussama

**Comment by yurymalkov** [comment]
Got it. 
Thank you for your work and a great evening for you too!

**Comment by hussamaa** [comment]
@yurymalkov, thank you for the great job. Keep it up!

**Pull request closed without merging**
