### PR TITLE
Mark deletion supported

### PR DESCRIPTION
**Pull request by ctero-graham**
Support deletion by adding a "deleted" mark to the elements.

The higher 8 bits of the list link size at level 0 will be used the store the mark, therefore, the link size has to be limited to the lower 24 bits, however, still large enough for almost all cases.

### CODE REVIEW

**Comment by yurymalkov** [comment]
Hi @ctero-graham,
Thank you!
I'll check the PR and provide feedback soon.

**Comment by ctero-graham** [comment]
Hi @yurymalkov 
Any comments?

**Comment by yurymalkov** [comment]
Hi @ctero-graham.
I am very sorry, I was very busy. I'll test and review the PR within few days.

Can you please make a PR against the branch "develop"?

**Comment by ctero-graham** [comment]
> Hi @ctero-graham.
> I am very sorry, I was very busy. I'll test and review the PR within few days.
> 
> Can you please make a PR against the branch "develop"?

Sure，I'll make a new one and close this.

**Comment by yurymalkov** [comment]
Thanks!

**Pull request closed without merging**
